app.config(function($stateProvider,$urlRouterProvider){
  $urlRouterProvider.otherwise('home');
  $stateProvider
    .state('main',{
      url:'/',
      views:{
        '':{templateUrl:'views/main.html'},
      }
    })
    .state('main.home',{
      url:'home',
      views:{
        'content@main':{templateUrl:'views/home.html'}
      }
    })
    .state('main.home.detail',{
      url:'/detail/:which',
      views:{
        'content@main':{templateUrl:'views/detail.html'}
      }
    })
    .state('main.home.detail.views',{
      url:'/views',
      views:{
        'content@main':{templateUrl:'views/views.html'}
      }
    })
    .state('main.home.detail.food',{
      url:'/food/:name',
      views:{
        'content@main':{templateUrl:'views/food.html'}
      }
    })
    .state('main.home.detail.house',{
      url:'/house/:name',
      views:{
        'content@main':{templateUrl:'views/house.html'}
      }
    })
    .state('main.home.city',{
      url:'/city',
      views:{
        'content@main':{templateUrl:'views/city.html'}
      }
    })
    .state('main.home.city.confirm',{
      url:'/confirm',
      views:{
        'content@main':{templateUrl:'views/confirm.html'}
      }
    })
    .state('main.home.city.confirm.infor',{
      url:'/infor',
      views:{
        'content@main':{templateUrl:'views/infor.html'}
      }
    })
    .state('main.home.city.confirm.infor.startcity',{
      url:'/startcity',
      views:{
        'content@main':{templateUrl:'views/startcity.html'}
      }
    })
    .state('main.home.city.confirm.infor.backcity',{
      url:'/backcity',
      views:{
        'content@main':{templateUrl:'views/backcity.html'}
      }
    })
    .state('main.home.city.confirm.infor.choseroute',{
      url:'/choseroute',
      views:{
        'content@main':{templateUrl:'views/choseroute.html'}
      }
    })
    .state('main.home.city.confirm.infor.choseroute.dazhi',{
      url:'/dazhi',
      views:{
        'content@main':{templateUrl:'views/dazhi.html'}
      }
    })
})
